name: define_project_name_here

services:
  rstudio-server:
    # Define container name
    container_name: define_container_name_here
    # Docker image is retrieved from docker hub repo "dncr/rstudio-server".
    # See GitHub repo "https://github.com/dncR/rstudio-server" for more details about image build.
    image: dncr/rstudio-server:${R_VERSION}-${UBUNTU_VERSION}
    # Environment variables used within docker container and/or in this compose file.
    env_file:
      - .env
    # Additional environment variables which are not allowed to be exported via "env_file".
    environment:
      # Set a password for RStudio Server login
      - PASSWORD=rstudio..
    # Set a restart policy for docker container
    restart: "unless-stopped"
    # Set 'root' as active bash user of the docker container. This does not mean that the user "rstudio"
    # is not created. We set 'root' user to trigger some codes without error using root priviledges
    # while building docker images. It may be commented if not building the image but running the container
    # using pre-built image from dncr/rstudio-server.
    user: 'root'
    # Bind a local port to RStudio-Server port 8787.
    ports:
      - '7000:8787'
    # Set external volumes.
      # User-specific container (external volume). Files in this folder will be stored as an external volume
      # out of docker container. If docker container was removed, external files will be remained in the main 
      # computer. Multiple volumes can be defined. Note that the user name within docker container is "rstudio".
    volumes:
      - /SourcePath/:/home/rstudio/externalvolume
      - /SourcePath2/:/home/rstudio/externalvolume
