# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit fastml.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)


## ----leakage-workflow, fig.cap="Illustration of a leaky cross-validation workflow caused by global preprocessing.", fig.alt="Two side-by-side workflow diagrams compare leaky and guarded cross-validation. The leaky workflow applies preprocessing before resampling, while the guarded workflow estimates preprocessing separately inside each fold before evaluation.", out.width="100%"----
knitr::include_graphics("figures/leaky_cv_workflow_AB.png")


## ----workflow_simulation_comparison, eval=FALSE, echo=TRUE--------------------
# library(dplyr)
# library(rsample)
# library(recipes)
# library(parsnip)
# library(workflows)
# library(yardstick)
# library(purrr)
# library(fastml)
# library(ggplot2)
# library(tidyr)
# library(patchwork)
# 
# set.seed(2025)
# 
# n_sims <- 100
# n_sites <- 10
# n_per_site <- 100
# 
# run_iteration <- function(seed) {
#   set.seed(seed)
# 
#   total_n <- n_sites * n_per_site
#   sites <- rep(paste0("S", 1:n_sites), each = n_per_site)
# 
#   z <- rnorm(total_n, mean = 0, sd = 1)
#   site_offsets <- rnorm(n_sites, mean = 5, sd = 5)
#   x_observed <- z + rep(site_offsets, each = n_per_site)
# 
#   prob <- 1 / (1 + exp(-(z * 2)))
#   y <- factor(ifelse(runif(total_n) < prob, "Case", "Control"),
#     levels = c("Control", "Case")
#   )
# 
#   df <- tibble(
#     site = factor(sites),
#     outcome = y,
#     x = x_observed
# )
# 
#   # Leaky workflow:
#   # Global site-wise standardization before resampling
#   df_leaky <- df %>%
#     group_by(site) %>%
#     mutate(x_scaled = as.numeric(scale(x))) %>%
#     ungroup()
# 
#   folds_leaky <- group_vfold_cv(
#     df_leaky,
#     group = "site",
#     v = n_sites
#   )
# 
#   auc_leaky <- map_dbl(folds_leaky$splits, function(spl) {
#     model <- rand_forest(trees = 50) %>%
#       set_mode("classification") %>%
#       set_engine("ranger") %>%
#       fit(outcome ~ x_scaled, data = analysis(spl))
# 
#     predict(model, assessment(spl), type = "prob") %>%
#       bind_cols(assessment(spl)) %>%
#       roc_auc(truth = outcome, .pred_Case,
#               event_level = "second") %>%
#       pull(.estimate)
#   })
# 
#   grouped_folds <- rsample::group_vfold_cv(
#     df, group = site, v = n_sites
#   )
# 
#   # Guarded workflow:
#   # Fold-specific preprocessing (fastml)
#   guarded_model <- fastml(
#     data = df,
#     label = "outcome",
#     algorithms = "rand_forest",
#     resamples = grouped_folds,
#     metric = "roc_auc",
#     event_class = "second",
#     recipe = recipe(outcome ~ x + site, data = df) %>%
#       update_role(site, new_role = "id") %>%
#       step_normalize(x),
#     tune_params = list(
#       rand_forest = list(ranger = list(trees = 50))
#     )
#   )
#   tibble(
#     Leaky_AUC = mean(auc_leaky),
#     Guarded_AUC = guarded_model$performance$rand_forest$ranger %>%
#       filter(.metric == "roc_auc") %>%
#       pull(.estimate)
#   )
# }


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# simulation_results <- map_dfr(1:n_sims, run_iteration)


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# summary_stats <- simulation_results %>%
#   summarise(
#     Mean_Leaky = mean(Leaky_AUC),
#     SD_Leaky = sd(Leaky_AUC),
#     Mean_Guarded = mean(Guarded_AUC),
#     SD_Guarded = sd(Guarded_AUC)
#   )
# 
# print(summary_stats)


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# diffs <- simulation_results$Leaky_AUC - simulation_results$Guarded_AUC
# mean_diff <- mean(diffs)
# se_diff <- sd(diffs) / sqrt(n_sims)
# ci <- mean_diff + c(-1, 1) * qt(0.975, df = n_sims - 1) * se_diff
# 
# mean_diff
# ci


## ----figure_2_codes, eval=FALSE, echo=TRUE------------------------------------
# p1 <- simulation_results %>%
#   pivot_longer(cols = c(Leaky_AUC, Guarded_AUC)) %>%
#   ggplot(aes(x = name, y = value, fill = name)) +
#   geom_violin(alpha = 0.3, trim = FALSE) +
#   geom_boxplot(width = 0.2, alpha = 0.8) +
#   scale_fill_manual(values = c("#99CC99", "#FF9999")) +
#   labs(title = "A. AUC Distribution", y = "ROC AUC", x = NULL) +
#   theme_minimal() + theme(legend.position = "none")
# 
# p2 <- ggplot(simulation_results) +
#   geom_segment(aes(
#     x = "Leaky",
#     xend = "Guarded",
#     y = Leaky_AUC,
#     yend = Guarded_AUC
#   ),
#   alpha = 0.3) +
#   geom_point(aes(x = "Leaky", y = Leaky_AUC), color = "#FF9999") +
#   geom_point(aes(x = "Guarded", y = Guarded_AUC), color = "#99CC99") +
#   labs(title = "B. Paired Drop", y = "ROC AUC", x = NULL) +
#   theme_minimal()
# 
# p1 + p2


## ----auc-leaky-vs-guarded, fig.cap="Preprocessing placement under grouped cross-validation: (A) ROC AUC distributions for leaky versus guarded workflows; (B) paired ROC AUC showing inflation with global preprocessing.", fig.alt="A two-panel figure. Panel A compares the distribution of ROC AUC values for leaky and guarded workflows across simulation runs. Panel B shows paired points and connecting segments, with most guarded values lower than the corresponding leaky values.", out.width="100%"----
knitr::include_graphics("figures/auc-leaky-vs-guarded.png")


## ----fastml-object-table, results="asis"--------------------------------------
fastml_object_table <- data.frame(
  Slot = c(
    "`models`",
    "`preprocessor`",
    "`predictions`",
    "`performance`",
    "`metric`",
    "`best_model_name`",
    "`resampling_plan`",
    "`raw_train_data`, `raw_test_data`",
    "`processed_train_data`, `processed_test_data`",
    "`audit`"
  ),
  Description = c(
    "Fitted model objects, indexed by algorithm and engine",
    "Stored preprocessing object",
    "Stored predictions from evaluation",
    "Aggregated performance metrics",
    "Primary evaluation metric",
    "Identifier of the default reference model",
    "Resampling specification (e.g., CV folds, repeats)",
    "Data partitions used for fitting/evaluation (when retained)",
    "Preprocessed partitions (when retained)",
    "Audit log entries and a flagged indicator"
  ),
  `Practical guarantee` = c(
    "Models are stored as fitted objects; downstream `predict` and `plot` methods are intended to use stored fits rather than refitting. Reproducibility depends on package versions and environment consistency.",
    "The stored preprocessor corresponds to the final training split (`train_data`), not to per-fold analysis subsets. Fold-local preprocessing occurs inside resampling when that path is used, but the stored final preprocessor is trained on the training split used for the final fit.",
    "Predictions stored here are the holdout or test predictions produced during evaluation. Training-set predictions and per-fold resampling predictions are not necessarily stored in the same slot by default.",
    "Metrics are computed from evaluation outputs, typically holdout or test predictions. If resampling is used, summary performance reflects the resampling results recorded by the resampling layer.",
    "Defines the main comparison target used in model reporting within the object.",
    "A presentation or default-selection label; it should not be interpreted as changing how metrics were computed.",
    "Encodes how resampling was defined when resampling is executed; used for reporting and consistency.",
    "Enables inspection of the exact splits used. This supports auditability, but the object may include data and therefore is not data-free.",
    "Supports inspection of preprocessing output and helps detect unexpected preprocessing behavior; this is an audit convenience, not a mathematical guarantee of leakage absence.",
    "When `audit_mode = TRUE`, the audit structure records security-related warnings or flags. It is not a full training provenance log."
  ),
  check.names = FALSE
)
knitr::kable(
  fastml_object_table,
  caption = "Core components of a `fastml` object and associated guarantees.",
  booktabs = TRUE,
  escape = FALSE
)


## ----framework-comparison-table, results="asis"-------------------------------
framework_comparison_table <- data.frame(
  Feature = c(
    "Interface philosophy",
    "Preprocessing and leakage control",
    "Survival analysis support",
    "Extensibility and safety"
  ),
  caret = c(
    "Unified wrapper; function-based syntax such as `train`.",
    "Manual; users must prevent leakage explicitly.",
    "Basic support, primarily Cox proportional hazards.",
    "Standard execution inside the R session."
  ),
  tidymodels = c(
    "Modular pipeline built from recipes, model specifications, workflows, and resamples.",
    "Optional and user-assembled; leakage-safe workflows are possible but not enforced.",
    "Expanding support, including extensions such as \\CRANpkg{censored}.",
    "Standard execution inside the R session."
  ),
  mlr3 = c(
    "Object-oriented design with tasks, learners, and graphs.",
    "Robust graph-based pipelines can express leakage-safe evaluation.",
    "Extensive support via extensions such as \\CRANpkg{mlr3proba}.",
    "Standard execution inside the R session."
  ),
  h2o = c(
    "Integrated AutoML engine.",
    "Automated preprocessing and evaluation inside the H2O engine.",
    "Standard survival support including Cox and AFT variants.",
    "Engine-isolated execution on the Java backend."
  ),
  fastml = c(
    "Guarded facade with a simplified single-function call (`fastml`).",
    "Guarded resampling re-estimates preprocessing within folds on supported execution paths.",
    "Unified interface spanning penalized Cox, native XGBoost AFT, and piecewise exponential models.",
    "Preventive recipe validation plus optional audit instrumentation."
  ),
  check.names = FALSE
)
names(framework_comparison_table) <- c(
  "Feature",
  "\\\\CRANpkg{caret}",
  "\\\\CRANpkg{tidymodels}",
  "\\\\CRANpkg{mlr3}",
  "\\\\CRANpkg{h2o}",
  "\\\\CRANpkg{fastml}"
)
knitr::kable(
  framework_comparison_table,
  caption = "Architectural and functional comparison of major R machine learning frameworks.",
  booktabs = TRUE,
  escape = FALSE
)
cat("\n\n\\emph{Note}: \\CRANpkg{mlr3proba} is currently removed from CRAN; archived versions remain available.\n")


## ----benchmark-a-split, eval=TRUE, include=FALSE------------------------------
library(mlbench)
library(rsample)

data("PimaIndiansDiabetes2")

set.seed(123)
split <- initial_split(PimaIndiansDiabetes2, strata = "diabetes")
train_data <- training(split)
test_data  <- testing(split)


## ----benchmark-a-tidymodels, eval=TRUE, echo=TRUE-----------------------------
library(tidymodels)

rec <- recipe(diabetes ~ ., data = train_data) %>%
  step_impute_median(all_numeric_predictors()) %>%
  step_novel(all_nominal_predictors()) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_zv(all_predictors()) %>%
  step_center(all_numeric_predictors()) %>%
  step_scale(all_numeric_predictors())

log_spec <- logistic_reg() %>%
  set_engine("glm") %>%
  set_mode("classification")

wf <- workflow() %>%
  add_recipe(rec) %>%
  add_model(log_spec)

final_fit <- fit(wf, data = train_data)

preds <- predict(final_fit, new_data = test_data) %>%
  bind_cols(predict(final_fit, new_data = test_data, type = "prob")) %>%
  bind_cols(test_data)

multi_metric <- metric_set(
  accuracy, kap, f_meas, precision, 
  sens, spec, roc_auc
)

metrics_tm <- multi_metric(
  preds,
  truth = diabetes,
  estimate = .pred_class,
  .pred_pos,
  event_level = "second"
)

print(metrics_tm)


## ----benchmark-a-fastml, eval=TRUE, echo=TRUE---------------------------------
library(fastml)

fm <- fastml(
  train_data    = train_data,
  test_data     = test_data,
  label         = "diabetes",
  algorithms    = "logistic_reg",
  impute_method = "medianImpute",
  event_class   = "second"
)

fm$performance$logistic_reg


## ----external-survival-table, results="asis"----------------------------------
external_survival_table <- data.frame(
  Dataset = c("Lung (N = 228)", "Rotterdam (N = 2,982)", "Flchain (N = 7,874)"),
  `Cox PH (Baseline)` = c("0.631 +/- 0.064 (0.599 to 0.663)", "0.690 +/- 0.014 (0.683 to 0.697)", "0.794 +/- 0.013 (0.787 to 0.800)"),
  `Weibull AFT (Baseline)` = c("0.633 +/- 0.062 (0.601 to 0.664)", "0.690 +/- 0.014 (0.683 to 0.697)", "0.794 +/- 0.013 (0.788 to 0.801)"),
  `fastml (Penalized Cox)` = c("0.641 +/- 0.066 (0.607 to 0.674)", "0.695 +/- 0.015 (0.687 to 0.702)", "0.793 +/- 0.012 (0.787 to 0.799)"),
  `fastml (XGBoost AFT)` = c("0.618 +/- 0.050 (0.593 to 0.644)", "0.705 +/- 0.012 (0.699 to 0.711)", "0.795 +/- 0.014 (0.788 to 0.802)"),
  `fastml (RF Survival)` = c("0.644 +/- 0.061 (0.613 to 0.675)", "0.711 +/- 0.015 (0.704 to 0.719)", "0.799 +/- 0.013 (0.793 to 0.806)"),
  check.names = FALSE
)
knitr::kable(
  external_survival_table,
  caption = "Mean standardized Harrell's C-index +/- SD (95% CI) across data scales from the external benchmark.",
  booktabs = TRUE,
  escape = FALSE
)


## ----case-study-a, eval=TRUE, echo=TRUE---------------------------------------
library(fastml)
library(mlbench)
library(dplyr)

set.seed(2025)

data("BreastCancer")

bc <- BreastCancer %>%
  select(-Id) %>%           # exclude identifier
  filter(!is.na(Class)) %>% # ensure outcome observed
  na.omit()                 # simplify this case study: complete-case analysis

fm_bc <- fastml(
  data          = bc,
  label         = "Class",
  algorithms    = c("logistic_reg", "rand_forest", "xgboost"),
  metric        = "roc_auc",
  event_class   = "second",
  impute_method = "medianImpute"
)

summary(fm_bc, type = "metrics")
plot(fm_bc, type = "roc")


## ----eval=TRUE, echo=TRUE-----------------------------------------------------
# Optional: explanation outputs depend on installed explainers 
#           and model compatibility
fastexplain(fm_bc, algorithm = "rand_forest")


## ----case-study-b, eval=TRUE, echo=TRUE---------------------------------------
library(fastml)
library(bonsai) 
library(NHANES)
library(dplyr)

set.seed(2025)

data("NHANES")

df <- NHANES %>%
  select(
    BPSysAve,
    Age, Gender, BMI, Race1, Education, Poverty,
    SleepHrsNight, PhysActive, Smoke100, TotChol, Diabetes
  ) %>%
  filter(!is.na(BPSysAve))

fm_bp <- fastml(
  data              = df,
  label             = "BPSysAve",
  algorithms        = c("elastic_net", "rand_forest", "lightgbm"),
  metric            = "rmse",
  impute_method     = "medianImpute",
  resampling_method = "cv",
  folds             = 5,
  tune_params       = list(
    elastic_net = list(
      glmnet = list(
        penalty = c(0.01, 0.1),
        mixture = c(0.0, 0.5, 1.0)  # ridge, elastic net, lasso
      )
    ),
    rand_forest = list(
      ranger = list(
        mtry  = c(2, 3, 5),
        min_n = c(20, 50),
        trees = c(100)
      )
    ),
    lightgbm = list(
      lightgbm = list(
        num_leaves    = c(20, 31),
        learning_rate = c(0.05, 0.1)
      )
    )
  )
)

summary(fm_bp)

