results_list <- list(
  data_overview             = data_overview,
  summary_stats             = summary_stats,
  distribution_tests        = distribution_tests_results,
  freq_tables               = freq_tables,
  missing_data              = missing_data,
  duplicated_rows           = dup_count,
  class_imbalance           = class_imbalance,
  correlation_matrix        = correlation_matrix,
  zero_variance_cols        = zero_variance_cols,
  potential_id_cols         = potential_id_cols,
  date_time_cols            = date_time_cols,
  high_corr_pairs           = high_corr_pairs,
  outlier_method            = outlier_method,
  outlier_summary           = outlier_summary
)



report_rmd_content <- c(
  "---",
  "title: \"fastexplore EDA Report\"",
  "author: \"fastexplore\"",
  "date: \"`r Sys.Date()`\"",
  "output:",
  "  html_document:",
  "    toc: true",
  "    number_sections: true",
  "  pdf_document:",
  "    toc: true",
  "    number_sections: true",
  "---",
  "",
  "```{r setup, include=FALSE}",
  "knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)",
  "```",
  "",
  "## Data Overview",
  "",
  "```{r data-overview}",
  "results_list$data_overview",
  "```",
  "",

  "## Summary Statistics",
  "",
  "```{r summary-stats}",
  "if (!is.null(results_list$summary_stats)) {",
  "  results_list$summary_stats",
  "} else {",
  "  \"No numeric columns or summary statistics available.\"",
  "}",
  "```",
  "",

  "## Distribution Checks (Normality Tests)",
  "",
  "```{r distribution-checks}",
  "if (!is.null(results_list$distribution_tests)) {",
  "  results_list$distribution_tests",
  "} else {",
  "  \"No distribution tests available.\"",
  "}",
  "```",
  "",

  "## Frequency Tables",
  "",
  "```{r freqeuncy-tables}",
  "if (!is.null(results_list$freq_tables)) {",
  "  results_list$freq_tables",
  "} else {",
  "  \"No frequency tables available.\"",
  "}",
  "```",
  "",

  "## Missing Data Analysis",
  "",
  "```{r missing-data-analysis}",
  "if (!is.null(results_list$missing_data)) {",
  "  results_list$missing_data",
  "} else {",
  "  \"No missing data info available.\"",
  "}",
  "```",
  "",

  "## Duplicated Rows",
  "",
  "```{r duplicated-rows}",
  "if (!is.null(results_list$duplicated_rows)) {",
  "  results_list$duplicated_rows",
  "} else {",
  "  \"No duplicated rows available.\"",
  "}",
  "```",
  "",

  "## Class Imbalance (if label is provided)",
  "",
  "```{r class-imbalance}",
  "if (!is.null(results_list$class_imbalance)) {",
  "  results_list$class_imbalance",
  "} else {",
  "  \"No class imbalance info available.\"",
  "}",
  "```",
  "",

  "## Class Imbalance (if label is provided)",
  "",
  "```{r class-imbalance}",
  "if (!is.null(results_list$class_imbalance)) {",
  "  results_list$class_imbalance",
  "} else {",
  "  \"No class imbalance info available.\"",
  "}",
  "```",
  "",

  "## Correlation Matrix",
  "",
  "```{r correlation-matrix}",
  "if (!is.null(results_list$correlation_matrix)) {",
  "  results_list$correlation_matrix",
  "} else {",
  "  \"No correlation matrix available.\"",
  "}",
  "```",
  "",

  "## Zero/Near-Zero Variance",
  "",
  "```{r zero-variance}",
  "if (!is.null(results_list$zero_variance_cols)) {",
  "  results_list$zero_variance_cols",
  "} else {",
  "  \"No zero variance variables available.\"",
  "}",
  "```",
  "",

  "## Potential ID Columns",
  "",
  "```{r id-columns}",
  "if (!is.null(results_list$potential_id_cols)) {",
  "  results_list$potential_id_cols",
  "} else {",
  "  \"No ID columns available.\"",
  "}",
  "```",
  "",

  "## Potential Date Time Columns",
  "",
  "```{r date-columns}",
  "if (!is.null(results_list$date_time_cols)) {",
  "  results_list$date_time_cols",
  "} else {",
  "  \"No date time columns available.\"",
  "}",
  "```",
  "",

  "## High-Correlation Pairs",
  "",
  "```{r high-corr-pairs}",
  "if (!is.null(results_list$high_corr_pairs)) {",
  "  results_list$high_corr_pairs",
  "} else {",
  "  \"No high correlation pairs available.\"",
  "}",
  "```",
  "",


  "## Outlier Summary",
  "",
  "```{r outlier-summary}",
  "if (!is.null(results_list$outlier_summary)) {",
  "  results_list$outlier_summary",
  "} else {",
  "  \"No outlier summary available.\"",
  "}",
  "```",
  "",
)
